import {DarkTheme, DefaultTheme} from "@react-navigation/native";

export const COLORS = {
    dark: {
        ...DarkTheme,
        colors: {
            ...DarkTheme.colors,
            background: 'rgb(27,27,27)',
            text: '#ffffff',
            primary: '#1144AA',
            underlayForPrimary: '#0537aa',
            secondary: '#969fae',
            underlaySecondary: '#858a98',
            info: '#31ccec',
            accent: '#4575D4',
            positive: '#21ba45',
            negative: '#c10015',
            warning: '#f2c037',
            activeTab: '#4575D4',
            closeBtn: '#999aa1',
            deleteBtn: '#f44336',
            underlayForDeleteBtn: '#c11a12',
            listElement: '#5b86e5',
            underlayForListElement: '#4371d666',
            darkModalBackground: '#302f2f',
            darkAgendaItemBackground: '#232323',
        },
    },
    light: {
        ...DefaultTheme,
        colors: {
            ...DefaultTheme.colors,
            background: '#ffffff',
            text: '#ffffff',
            primary: '#1144AA',
            underlayForPrimary: '#0537aa',
            secondary: '#969fae',
            underlaySecondary: '#858a98',
            info: '#31ccec',
            accent: '#4575D4',
            positive: '#21ba45',
            negative: '#c10015',
            warning: '#f2c037',
            activeTab: '#4575D4',
            closeBtn: '#999aa1',
            deleteBtn: '#f44336',
            underlayForDeleteBtn: '#c11a12',
            listElement: '#5b86e5',
            underlayForListElement: '#4371d666',
            agendaItemBackground: '#f2f2f2',
        },
    }
};